language: node_js
node_js:
- 8.11.3
- node
addons:
  browserstack:
    username: anton1175
    access_key:
      secure: GDWyuhXnmq3HeOEHK+MBM0yIONtnn1k91KcMnXyrtn8DhTXHw5RbPKx+xnffr15K3t4QpQyIR2hXsOQ09U4DEQ+6mp22LGvRqtJrd6SOlY0Zh1TZqHrSJarASERM0W5TgtL+6mqedx/Jim0O0dPPbDEfXFXcrToOLVnzvoM6tHt2dQ5mvBirLlbCIvQD6iOMxaDo/Fd3MIJaJGRoFYq7PNB8imjrNA1dT31BcD+eEZceprrZFXB20+WLBJVFJag7XKiFxHULPl2lz56wGR5JsvExns4pdlxgioT24E72cIPkG1NfRcqMDEpIP1DqxmSXzwfy9/E40i4AakfdFO5DinmAgMzAyNqVmjH2MEB1IQN2taKCGK/qL9arVsECslQbLba+18BE6Uswp9qAQkGC2iFCbTqMUEX4B604pLK4xZgkatadMaWSVV5sd5my/FMifn1cXIeswNc6AGUlfCs2B5IP635UGinQYLrap3ItT5t1fLkBhLqz785vJem2o1wKVuD03kXrvQLwYa6Up2WZkabrZZ7FhusyC4R/mTVluu6CJVk3YaStdM+PxfWxse9i8v3DQLUHZGhOmrr5b0xUyTcq1DlPR3b30f5/4pWdCMPF0AXYPScq8/m07DLanvmKjjD+lkXcQOqax5Z4Tiqtzdi7h4rXUBY5WFnX2TsdLus=
before_install:
- openssl aes-256-cbc -K $encrypted_0e9b775308a9_key -iv $encrypted_0e9b775308a9_iv
  -in .env.test.enc -out .env.test -d
jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: cross-env NODE_ENV=test jest --config=jest.config.json --coverage && cat
      ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: heroku
  api_key:
    secure: qRWqkG1I8oq8MMniJK+ckXs7I8r3lkAtdDudsiq9DtRfLUFPdkNDFP0Qq4GhZ82ke6rQwuE4MZuEGzv3v0d/G4a3RSZ6JTejAU0TOEeUMwSZojgvUgU6IKUB+3kzADshyN3Vnj/1BbHIXyIV56FeXyjQUDgWSgO8y9yeWzmbFAZlTjEKOzi5T9/zoMKVmA3PhyNDxFnI2RPGiSNvrPi8M8QL0nJch/ZFmdJj6lF1eFjPw7eWn+KDG63otJZ9h5n6WB1Xm9tS7vIWJ84G9FsvdeW5rSJNwFz0F+Jn5FjnaQmOo4WYbnH5vBW/fds381yQQnoMpoR+ASiP3xre2z6u+qFo2fO70vlfTtN4x5QiK0u8i5+05R5tOMfNcvb5HzmMRmYEz4jkGkMHqXA3mOaj764XWmMJMBzdiOu5xxl2PF/6UYJSIJmze3fSZ4Lnrbcx5djJbkwAcmPIC9Hhp6VfwJbq91uMaqzXszlu/NtMtykJAt4hHYD5BOzO+Z/3Tl/C1wAGFWS4mgiZjozI2jhN9Kkql6YNVpXwWjvn4/bYeceZCFzMaVk/nF2g0LTdLnoyzS0WcLOfKt+ypQmpL9NQKz+BQF9+vEUDwsj9hbIRb7/6Tr2lnMPuFnkXw4J/qdwXk8UwRpb9k+qYjbNA/fLYzP1zW/Xi8n3yDPfeyUetavI=
  app: expensemap
  on:
    repo: antonzabirko/expensemap
